#!name=自定义DNS模块
#!desc=AliDNS + 国内直连

[General]
# DNS 覆写
dns-server = quic://223.5.5.5,https://dns.alidns.com/dns-query

[Host]
# 指定域名解析
dns.alidns.com = 223.5.5.5,223.6.6.6,2400:3200:baba::1,2400:3200::1

[Rule]
# 苹果服务
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list,DIRECT
# WeChat服务
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list,DIRECT
# 抖音服务
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/DouYin/DouYin.list,DIRECT
# 国内规则
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/China/China.list,DIRECT
# 局域网络
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Lan/Lan.list,DIRECT
